---
apiVersion: v1
appVersion: "0.1.0"
description: Classification model predicting the categories of 2D or 3D images using the AUCMEDI framework.
name: aucmedi-prediction-workflow
version: "0.0.0"
keywords:
- kaapanaworkflow
annotations:
  ui-visible-name: "AUCMEDI Prediction"