---
apiVersion: v1
appVersion: "0.1.0"
description: Classification model evaluating the training on 2D or 3D images using the AUCMEDI framework.
name: aucmedi-evaluation-workflow
version: "0.0.0"
keywords:
- kaapanaworkflow
annotations:
  ui-visible-name: "AUCMEDI Evaluation"